name: widget-test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
jobs:
  widget-test:
    name: flutter widget test
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: set up flutter-action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.2'
      - run: flutter pub get
        working-directory: ./scheduler
      - name: flutter widget test
        run: flutter test test/widget_test.dart
        working-directory: ./scheduler
